# SyntheticMarket realization for antitrust's native synthetic-market design.
#
# The ownership-adjusted derivative system and Logit normalization are
# economic-model responsibilities and remain in this adapter.

`%||%` <- function(x, y) if (is.null(x)) y else x

.antitrust_synthetic_logit_spec <- function(spec) {
  if (inherits(spec, "antitrust_model_spec")) return(spec)
  if (is.character(spec) && length(spec) == 1L) {
    return(model_spec(spec, "bertrand"))
  }
  if (is.list(spec) && !is.null(spec$demand)) {
    return(model_spec(spec$demand, spec$conduct %||% spec$supply %||% "bertrand",
                       spec$variant %||% "standard"))
  }
  stop("'spec' must be an antitrust model_spec or a Logit model descriptor")
}

.antitrust_synthetic_foc_solution <- function(shares, ownership) {
  derivative <- diag(shares) - tcrossprod(shares)
  ## D is symmetric for Logit, but retain the explicit transpose to make the
  ## ownership/derivative orientation visible in the implementation.
  G <- t(ownership * derivative)
  n <- length(shares)
  rank_tolerance <- sqrt(.Machine$double.eps)
  foc_rank <- qr(G, tol = rank_tolerance)$rank
  foc_condition_limit <- 1 / rank_tolerance
  foc_condition_number <- tryCatch(
    kappa(G, exact = TRUE),
    error = function(e) Inf
  )
  if (foc_rank < n || !is.finite(foc_condition_number) ||
      foc_condition_number > foc_condition_limit) {
    stop(
      "ownership-adjusted Logit FOC system is singular or ill-conditioned",
      " (rank = ", foc_rank, "/", n,
      ", condition number = ", format(foc_condition_number, digits = 6),
      ", limit = ", format(foc_condition_limit, digits = 6), ")"
    )
  }
  z <- tryCatch(solve(G, shares), error = function(e) e)
  if (inherits(z, "error") || any(!is.finite(z))) {
    stop("ownership-adjusted Logit FOC system is singular or non-finite: ",
         if (inherits(z, "error")) conditionMessage(z) else "non-finite solution")
  }
  list(
    G = G,
    z = z,
    rank = foc_rank,
    condition_number = foc_condition_number,
    condition_limit = foc_condition_limit
  )
}

#' Realize a SyntheticMarket under multi-product Bertrand Logit
#'
#' This is the first model-specific synthetic-market adapter. It accepts a
#' `SyntheticMarket` from antitrust and uses the full product-level
#' ownership-adjusted Logit Bertrand FOCs. The active reference product is
#' included in the system and only its mean utility is normalized to zero.
#'
#' In observed mode, the cost vector and proportional reference margin identify
#' the price coefficient and implied equilibrium prices. In
#' primitives mode, `alpha` must be in the market truth or be supplied in
#' `...`.
#'
#' @param market A `SyntheticMarket` generated by [fake_market()].
#' @param spec An `antitrust_model_spec`, a model name, or a descriptor list.
#' @param alpha Optional known Logit price coefficient.
#' @param allow_negative_costs In primitives mode, permit inferred negative
#'   costs when `TRUE`; observed costs are always supplied and positive.
#' @param foc_tolerance Numerical tolerance recorded for the FOC check.
#' @param ... Additional arguments, including `alpha` and safeguards.
#' @return A new realized `SyntheticMarket` with markups, costs, mean values,
#'   recovered parameters, and FOC diagnostics.
#' @export
realize_market.SyntheticMarket <- function(market, spec, alpha = NULL,
                                           allow_negative_costs = FALSE,
                                           foc_tolerance = 1e-8, ...) {
  if (!is_SyntheticMarket(market)) {
    stop("'market' must be a SyntheticMarket")
  }
  model <- .antitrust_synthetic_logit_spec(spec)
  if (!identical(model$demand, "logit") || !identical(model$conduct, "bertrand") ||
      !identical(model$variant, "standard")) {
    stop("the antitrust SyntheticMarket adapter currently supports standard Bertrand Logit only")
  }
  if (length(allow_negative_costs) != 1L || is.na(allow_negative_costs)) {
    stop("'allow_negative_costs' must be a single logical value")
  }
  if (length(foc_tolerance) != 1L || !is.finite(foc_tolerance) || foc_tolerance <= 0) {
    stop("'foc_tolerance' must be a positive finite number")
  }

  shares <- as.numeric(market$shares)
  prices <- as.numeric(market$prices)
  observed_mode <- identical(market$design$mode, "observed")
  ownership <- as.matrix(market$ownership)
  n <- length(shares)
  ref <- market$design$reference_product
  if (length(ref) != 1L || !is.finite(ref) || ref != as.integer(ref) ||
      ref < 1L || ref > n) {
    stop("market design has an invalid reference product")
  }
  ref <- as.integer(ref)
  if (length(prices) != n || nrow(ownership) != n || ncol(ownership) != n ||
      any(!is.finite(shares)) || any(shares <= 0) ||
      (!observed_mode && (any(!is.finite(prices)) || any(prices <= 0))) ||
      abs(sum(shares) - 1) > 1e-10) {
    stop("Logit realization requires valid all-product shares and, in primitives mode, positive prices")
  }
  if (!isTRUE(all.equal(ownership, t(ownership))) ||
      any(!is.finite(ownership)) || any(!(ownership %in% c(0, 1)))) {
    stop("Logit realization requires a symmetric zero-one ownership matrix")
  }

  ## Rows of D_unit are demanded products and columns are prices. This matches
  ## antitrust::elast()'s documented orientation. The FOC for each price is
  ## s + t(O * D) %*% mu = 0, where O is symmetric product ownership.
  foc_solution <- .antitrust_synthetic_foc_solution(shares, ownership)
  G <- foc_solution$G
  z <- foc_solution$z

  known_alpha <- alpha
  if (is.null(known_alpha) && is.list(market$truth)) known_alpha <- market$truth$alpha
  if (is.null(known_alpha) && is.list(market$design$parameters)) {
    known_alpha <- market$design$parameters$alpha
  }
  if (observed_mode && !is.null(known_alpha)) {
    stop("observed mode identifies alpha from costs and the reference margin; omit 'alpha'")
  }
  if (!is.null(known_alpha)) {
    if (length(known_alpha) != 1L || !is.finite(known_alpha) || known_alpha >= 0) {
      stop("known Logit 'alpha' must be a finite negative scalar")
    }
    alpha_source <- "known-primitives"
    alpha_value <- as.numeric(known_alpha)
  } else {
    reference_margin <- market$observed$reference_margin
    costs <- market$observed$costs
    if (length(reference_margin) != 1L || !is.finite(reference_margin) ||
        reference_margin <= 0 || reference_margin >= 1 ||
        length(costs) != n || any(!is.finite(costs)) || any(costs <= 0)) {
      stop("observed mode requires positive costs and a proportional reference margin in (0, 1)")
    }
    reference_markup <- costs[ref] * reference_margin / (1 - reference_margin)
    alpha_value <- unname(-z[ref] / reference_markup)
    alpha_source <- "observed-reference-margin"
  }

  markup <- unname(-z / alpha_value)
  if (observed_mode) {
    costs <- as.numeric(market$observed$costs)
    prices <- costs + markup
  } else {
    costs <- prices - markup
  }
  if (any(!is.finite(markup)) || any(!is.finite(costs))) {
    stop("Logit realization produced non-finite markups or costs")
  }
  negative_cost <- costs < -sqrt(.Machine$double.eps)
  if (any(negative_cost) && !isTRUE(allow_negative_costs)) {
    stop("Logit realization implied negative marginal costs for product(s): ",
         paste(which(negative_cost), collapse = ", "),
         "; set 'allow_negative_costs = TRUE' to retain the experimental draw")
  }

  ## Match the current antitrust Logit convention exactly: utility is relative
  ## to the chosen reference product, while the price remains its observed
  ## positive level.
  mean_value <- log(shares / shares[ref]) - alpha_value * (prices - prices[ref])
  mean_value[ref] <- 0
  predicted_utility <- mean_value + alpha_value * (prices - prices[ref])
  predicted_shares <- exp(predicted_utility - max(predicted_utility))
  predicted_shares <- predicted_shares / sum(predicted_shares)

  foc <- as.vector(shares + G %*% (alpha_value * markup))
  foc_residual <- max(abs(foc))
  share_residual <- max(abs(predicted_shares - shares))
  if (!is.finite(foc_residual) || foc_residual > foc_tolerance) {
    stop("realized Logit market failed its all-product FOC check: residual = ",
         format(foc_residual, digits = 6))
  }

  products <- market$products
  products$markup <- unname(markup)
  products$cost <- unname(costs)
  products$margin <- unname(markup / prices)
  products$mean_value <- unname(mean_value)

  truth <- market$truth
  if (identical(alpha_source, "known-primitives")) {
    truth$alpha <- alpha_value
  }
  truth$generated_markup <- unname(markup)
  if (!observed_mode) truth$generated_cost <- unname(costs)
  truth$generated_mean_value <- unname(mean_value)

  diagnostics <- market$diagnostics
  diagnostics$equilibrium_status <- "realized"
  diagnostics$model <- model
  diagnostics$parameter_source <- alpha_source
  diagnostics$recovered_parameters <- list(alpha = alpha_value)
  diagnostics$parameter_error <- if (!is.null(market$truth$alpha)) {
    list(alpha = alpha_value - market$truth$alpha)
  } else list()
  diagnostics$foc <- unname(foc)
  diagnostics$foc_residual <- unname(foc_residual)
  diagnostics$foc_tolerance <- foc_tolerance
  diagnostics$foc_rank <- foc_solution$rank
  diagnostics$foc_condition_number <- foc_solution$condition_number
  diagnostics$foc_condition_limit <- foc_solution$condition_limit
  diagnostics$share_residual <- unname(share_residual)
  diagnostics$negative_cost_products <- which(negative_cost)
  diagnostics$reference_margin_residual <- if (observed_mode) {
    markup[ref] / prices[ref] - market$observed$reference_margin
  } else NA_real_
  diagnostics$costs_status <- if (any(negative_cost)) "negative-retained" else "non-negative"

  metadata <- market$metadata
  metadata$realization <- list(
    package = "antitrust",
    model = model$id,
    reference_product = ref,
    derivative_orientation = "rows are demanded products; columns are prices",
    ownership_adjustment = "transpose(ownership * derivative)",
    foc_rank = foc_solution$rank,
    foc_condition_number = foc_solution$condition_number,
    markup_units = "level price difference"
  )

  if (observed_mode) {
    products$price <- prices
    market$observed$prices <- prices
    market$observed$reference_price <- prices[ref]
    market$design$reference_price <- prices[ref]
  }
  if (!is.finite(share_residual) || share_residual > foc_tolerance) {
    stop("realized Logit market failed its share-reproduction check")
  }
  SyntheticMarket(
    design = market$design,
    firms = market$firms,
    products = products,
    ownership = ownership,
    shares = shares,
    prices = prices,
    observed = market$observed,
    truth = truth,
    diagnostics = diagnostics,
    metadata = metadata
  )
}
