# SyntheticMarket realization for the model-independent iopolicy package.
#
# This adapter intentionally lives in antitrust. The ownership-adjusted
# derivative system and Logit normalization are economic-model responsibilities
# and must not be copied into iopolicy.

`%||%` <- function(x, y) if (is.null(x)) y else x

.antitrust_synthetic_logit_spec <- function(spec) {
  if (inherits(spec, "antitrust_model_spec")) return(spec)
  if (is.character(spec) && length(spec) == 1L) {
    return(model_spec(spec, "bertrand"))
  }
  if (is.list(spec) && !is.null(spec$demand)) {
    return(model_spec(spec$demand, spec$conduct %||% spec$supply %||% "bertrand",
                       spec$variant %||% "standard"))
  }
  stop("'spec' must be an antitrust model_spec or a Logit model descriptor")
}

#' Realize a SyntheticMarket under multi-product Bertrand Logit
#'
#' This is the first model-specific synthetic-market adapter. It accepts a
#' `SyntheticMarket` from `iopolicy` and uses the full product-level
#' ownership-adjusted Logit Bertrand FOCs. The active reference product is
#' included in the system and only its mean utility is normalized to zero.
#'
#' In observed mode, `market$observed$outside_margin` identifies the common
#' output-market price coefficient through the selected supply model. In
#' primitives mode, `alpha` must be in the market truth or be supplied in
#' `...`.
#'
#' @param market A `SyntheticMarket` generated by `iopolicy`.
#' @param spec An `antitrust_model_spec`, a model name, or a descriptor list.
#' @param alpha Optional known Logit price coefficient.
#' @param allow_negative_costs If `FALSE`, fail when the implied level cost is
#'   negative.
#' @param foc_tolerance Numerical tolerance recorded for the FOC check.
#' @param ... Additional arguments, including `alpha` and safeguards.
#' @return A new realized `SyntheticMarket` with markups, costs, mean values,
#'   recovered parameters, and FOC diagnostics.
#' @export
realize_market.SyntheticMarket <- function(market, spec, alpha = NULL,
                                           allow_negative_costs = FALSE,
                                           foc_tolerance = 1e-8, ...) {
  if (!requireNamespace("iopolicy", quietly = TRUE)) {
    stop("the iopolicy package is required to realize a SyntheticMarket")
  }
  if (!iopolicy::is_SyntheticMarket(market)) {
    stop("'market' must be a SyntheticMarket")
  }
  model <- .antitrust_synthetic_logit_spec(spec)
  if (!identical(model$demand, "logit") || !identical(model$conduct, "bertrand") ||
      !identical(model$variant, "standard")) {
    stop("the antitrust SyntheticMarket adapter currently supports standard Bertrand Logit only")
  }
  if (length(allow_negative_costs) != 1L || is.na(allow_negative_costs)) {
    stop("'allow_negative_costs' must be a single logical value")
  }
  if (length(foc_tolerance) != 1L || !is.finite(foc_tolerance) || foc_tolerance <= 0) {
    stop("'foc_tolerance' must be a positive finite number")
  }

  shares <- as.numeric(market$shares)
  prices <- as.numeric(market$prices)
  ownership <- as.matrix(market$ownership)
  n <- length(shares)
  ref <- market$design$reference_product
  if (length(ref) != 1L || !is.finite(ref) || ref != as.integer(ref) ||
      ref < 1L || ref > n) {
    stop("market design has an invalid reference product")
  }
  ref <- as.integer(ref)
  if (length(prices) != n || nrow(ownership) != n || ncol(ownership) != n ||
      any(!is.finite(shares)) || any(shares <= 0) ||
      any(!is.finite(prices)) || any(prices <= 0) ||
      abs(sum(shares) - 1) > 1e-10) {
    stop("Logit realization requires positive finite all-product shares and prices summing to one")
  }
  if (!isTRUE(all.equal(ownership, t(ownership))) ||
      any(!is.finite(ownership)) || any(!(ownership %in% c(0, 1)))) {
    stop("Logit realization requires a symmetric zero-one ownership matrix")
  }

  ## Rows of D_unit are demanded products and columns are prices. This matches
  ## antitrust::elast()'s documented orientation. The FOC for each price is
  ## s + t(O * D) %*% mu = 0, where O is symmetric product ownership.
  D_unit <- diag(shares) - tcrossprod(shares, shares)
  G <- t(ownership * D_unit)
  z <- tryCatch(solve(G, shares), error = function(e) e)
  if (inherits(z, "error") || any(!is.finite(z))) {
    reason <- if (inherits(z, "error")) conditionMessage(z) else "non-finite inverse"
    stop("ownership-adjusted Logit FOC system is singular or non-finite: ", reason)
  }

  known_alpha <- alpha
  if (is.null(known_alpha) && is.list(market$truth)) known_alpha <- market$truth$alpha
  if (is.null(known_alpha) && is.list(market$design$parameters)) {
    known_alpha <- market$design$parameters$alpha
  }
  if (!is.null(known_alpha)) {
    if (length(known_alpha) != 1L || !is.finite(known_alpha) || known_alpha >= 0) {
      stop("known Logit 'alpha' must be a finite negative scalar")
    }
    alpha_source <- "known-primitives"
    alpha_value <- as.numeric(known_alpha)
  } else {
    outside_margin <- market$observed$outside_margin %||%
      market$observed$reference_markup
    if (length(outside_margin) != 1L || !is.finite(outside_margin) ||
        outside_margin <= 0) {
      stop("observed mode requires a strictly positive outside-product level margin")
    }
    alpha_value <- unname(-z[ref] / outside_margin)
    alpha_source <- "observed-outside-margin"
  }

  markup <- unname(-z / alpha_value)
  costs <- prices - markup
  if (any(!is.finite(markup)) || any(!is.finite(costs))) {
    stop("Logit realization produced non-finite markups or costs")
  }
  negative_cost <- costs < -sqrt(.Machine$double.eps)
  if (any(negative_cost) && !isTRUE(allow_negative_costs)) {
    stop("Logit realization implied negative marginal costs for product(s): ",
         paste(which(negative_cost), collapse = ", "),
         "; set 'allow_negative_costs = TRUE' to retain the experimental draw")
  }

  ## Match the current antitrust Logit convention exactly: utility is relative
  ## to the chosen reference product, while the price remains its observed
  ## positive level.
  mean_value <- log(shares / shares[ref]) - alpha_value * (prices - prices[ref])
  mean_value[ref] <- 0
  predicted_utility <- mean_value + alpha_value * (prices - prices[ref])
  predicted_shares <- exp(predicted_utility - max(predicted_utility))
  predicted_shares <- predicted_shares / sum(predicted_shares)

  foc <- as.vector(shares + G %*% (alpha_value * markup))
  foc_residual <- max(abs(foc))
  share_residual <- max(abs(predicted_shares - shares))
  if (!is.finite(foc_residual) || foc_residual > foc_tolerance) {
    stop("realized Logit market failed its all-product FOC check: residual = ",
         format(foc_residual, digits = 6))
  }

  products <- market$products
  products$markup <- unname(markup)
  products$cost <- unname(costs)
  products$margin <- unname(markup / prices)
  products$mean_value <- unname(mean_value)

  truth <- market$truth
  if (identical(alpha_source, "known-primitives")) {
    truth$alpha <- alpha_value
  }
  truth$generated_markup <- unname(markup)
  truth$generated_cost <- unname(costs)
  truth$generated_mean_value <- unname(mean_value)

  diagnostics <- market$diagnostics
  diagnostics$equilibrium_status <- "realized"
  diagnostics$model <- model
  diagnostics$parameter_source <- alpha_source
  diagnostics$recovered_parameters <- list(alpha = alpha_value)
  diagnostics$parameter_error <- if (!is.null(market$truth$alpha)) {
    list(alpha = alpha_value - market$truth$alpha)
  } else list()
  diagnostics$foc <- unname(foc)
  diagnostics$foc_residual <- unname(foc_residual)
  diagnostics$foc_tolerance <- foc_tolerance
  diagnostics$share_residual <- unname(share_residual)
  diagnostics$negative_cost_products <- which(negative_cost)
  diagnostics$observed_outside_margin <- market$observed$outside_margin %||%
    market$observed$reference_markup
  diagnostics$costs_status <- if (any(negative_cost)) "negative-retained" else "non-negative"

  metadata <- market$metadata
  metadata$realization <- list(
    package = "antitrust",
    model = model$id,
    reference_product = ref,
    derivative_orientation = "rows are demanded products; columns are prices",
    ownership_adjustment = "transpose(ownership * derivative)",
    markup_units = "level price difference"
  )

  iopolicy::SyntheticMarket(
    design = market$design,
    firms = market$firms,
    products = products,
    ownership = ownership,
    shares = shares,
    prices = prices,
    observed = market$observed,
    truth = truth,
    diagnostics = diagnostics,
    metadata = metadata
  )
}
